language: ruby
rvm:
  - 2.6.3

before_script:
  - chmod +x ./script/cibuild.sh

script: 
  - JEKYLL_ENV=production bundle exec jekyll build --destination site

branches:
  only:
  - release
  - /pages-(.*)

deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false

cache: bundler

notifications:
  email: true